# -*- coding: utf-8 -*-
"""TreinoDungeon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tg_3HQhhsjyA5tbm0pI89ahZvcTldRoW

Um heroi entra numa dungeon e enfrenta diversos tipos de inimigos sendo eles esqueletos, criaturas de fogo, criaturas de acido, etc.
Seu heroi consegue atacar de diferentes maneiras e usar a fraqueza dos inimigos
"""

import random

class Personagem:
  def __init__(self, nome, poder):
    self.nome = nome
    self.poder = poder

  def __str__(self):
    return (f"\nVocê está andando pela masmorra até que um {self.nome} aparece!")

  def mostrarbixos():
    print(heroi.nome, heroi.poder)

heroi = Personagem("Heroi", ["Espada", "Fogo", "Água"])
esqueleto = Personagem("Esqueleto", "Espada")
monstroAcido = Personagem("Monstro de Acído", "Acído")
monstroFogo = Personagem("Monstro de fogo", "Fogo")

listaMonstros = [esqueleto, monstroAcido, monstroFogo]

class Batalha:
  def introducao():
    print("Olá destemido Heroi, tome cuidado dentro da masmorra, você encontrará muitos perigos!\nAcredite, essa masmorra não tem fim, e quando você entra é impossivel sair")
    while True:
      startEscolha = input("Você tem certeza que deseja continuar?\n's' pra SIM e 'n' pra NÃO").lower()
      if startEscolha == "s":
        print("\nContinuando...")
        Batalha.sistemaBatalha()
        break
      elif startEscolha == "n":
        print("\nÓtima escolha Heroi")
        break
      else:
        print("\nEscolha inválida. Por favor, digite 's' ou 'n'.")

  def sistemaBatalha():
    while True:
      monstroEscolhido = random.choice(listaMonstros)
      print(monstroEscolhido)
      escolhaHeroi = int(input(f"\nVocê precisa fazer alguma coisa, o que você vai fazer?\n1 - {heroi.poder[0]}\n2 - {heroi.poder[1]}\n3 - {heroi.poder[2]}\n"))

      if escolhaHeroi == 1:
        if monstroEscolhido.poder == "Espada":
          print(f"Você ataca com sua espada!\nVocê derrotou o {monstroEscolhido.nome}")
        else:
          print("Você morreu!")
          Batalha.introducao()
      elif escolhaHeroi == 2:
        if monstroEscolhido.poder == "Acído":
          print(f"Você usou magia de fogo\nVocê derrotou o {monstroEscolhido.nome}")
        else:
          print("Você morreu!")
          Batalha.introducao()
      elif escolhaHeroi == 3:
        if monstroEscolhido.poder == "Fogo":
          print(f"Você usou magia de água\nVocê derrotou o {monstroEscolhido.nome}")
        else:
          print("Você morreu!")
          Batalha.introducao()
      else:
        print("Escolha uma opção válida:")






Batalha.introducao()